@startuml

interface TaskStorage
class PgTaskStorage
TaskStorage <|.. PgTaskStorage

class Allocator
interface CloudClient
class AwsCloudClient

Allocator *-- CloudClient
CloudClient <|.. AwsCloudClient
TaskStorage <.. Allocator

class Scheduler
class VmAssigner
interface JobOrderer
class FifoJobOrderer
class MinminJobOrderer
class MaxminJobOrderer
interface AllocatorStratagy
class BestFitAllocatorStratagy
class WorstFitAllocatorStratagy
class NextFitAllocatorStratagy
class FirstFitAllocatorStratagy

Scheduler *-- VmAssigner
VmAssigner *-- JobOrderer
JobOrderer <|.. FifoJobOrderer
JobOrderer <|.. MinminJobOrderer
JobOrderer <|.. MaxminJobOrderer
VmAssigner *-- AllocatorStratagy
AllocatorStratagy <|.. BestFitAllocatorStratagy
AllocatorStratagy <|.. WorstFitAllocatorStratagy
AllocatorStratagy <|.. NextFitAllocatorStratagy
AllocatorStratagy <|.. FirstFitAllocatorStratagy
VmAssigner *-- SlotSelector

class FailureDetector
Allocator <.. FailureDetector
TaskStorage <.. FailureDetector

class GrpcServer
class AgentApiSchedulerService
class PublicApiSchedulerService
TaskStorage <.. GrpcServer
GrpcServer *-- AgentApiSchedulerService
GrpcServer *-- PublicApiSchedulerService

class TaskRegistry
TaskRegistry o-- Allocator
TaskRegistry o-- Scheduler
TaskRegistry o-- FailureDetector
TaskRegistry o-- GrpcServer

@enduml
