services:
  db: # psql "host=localhost port=5432 dbname=postgres password=postgres user=postgres"
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ../libs/db/data/db_schema.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build:
      context: ../
      dockerfile: ./docker/server.Dockerfile
    depends_on:
      - db
    ports:
      - 50001:50001
    environment:
      PG_HOSTS: db
      PG_PASSWORD: postgres
      PG_USER: postgres
      PG_DB_NAME: postgres
      PG_POOL_SIZE: 10
      AWS_EC2_ACCESS_KEY_ID: "***"
      AWS_EC2_SECRET_KEY: "***"
      VMS_AGENT_ECR_ACCESS_KEY_ID: "***"
      VMS_AGENT_ECR_SECRET_KEY: "***"
      VMS_ZK_ADDRESS: "zk://3.137.201.107:2181,3.131.159.162:2181,3.17.63.120:2181/"
#      VMS_USE_ZK_DIST_LOCK: 1
      VMS_ADDRESS: server:50001
# Uncomment to test leader election via zookeeper
#  server1:
#    build:
#      context: ../
#      dockerfile: ./docker/server.Dockerfile
#    depends_on:
#      - db
#    ports:
#      - 50002:50001
#    environment:
#      PG_HOSTS: db
#      PG_PASSWORD: postgres
#      PG_USER: postgres
#      PG_DB_NAME: postgres
#      PG_POOL_SIZE: 10
#      AWS_EC2_ACCESS_KEY_ID: "***"
#      AWS_EC2_SECRET_KEY: "***"
#      VMS_AGENT_ECR_ACCESS_KEY_ID: "***"
#      VMS_AGENT_ECR_SECRET_KEY: "***"
#      VMS_ZK_ADDRESS: "zk://3.137.201.107:2181,3.131.159.162:2181,3.17.63.120:2181/"
#      VMS_USE_ZK_DIST_LOCK: 1
#      VMS_ADDRESS: server:50001
  agent:
    build:
      context: ../
      dockerfile: ./docker/agent.Dockerfile
    depends_on:
      - server
    environment:
      VMS_AGENT_SERVER_ADDRESS: server:50001
      VMS_AGENT_VM_ID: 1
      VMS_AGENT_AWS_ACCESS_KEY_ID: "***"
      VMS_AGENT_AWS_SECRET_ACCESS_KEY: "***"
      VMS_AGENT_AWS_REGION: "us-east-2"
      VMS_AGENT_AWS_BUCKET: "vms-job-results"
# Uncomment these lines to persist data on the local filesystem.
#   environment:
#     - PGDATA=/var/lib/postgresql/data/pgdata
#   volumes:
#     - ./pgdata:/var/lib/postgresql/data/pgdata
